//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;h4&gt;&lt;strong&gt;&lt;img src=&quot;https://i.imgur.com/zmm5CCm.png&quot; width=&quot;290&quot; height=&quot;284&quot; /&gt;&lt;/strong&gt;&lt;/h4&gt;
        ///&lt;h4&gt;&amp;nbsp;&lt;/h4&gt;
        ///&lt;p&gt;&lt;span style=&quot;color: #aa9260;&quot;&gt;&lt;strong&gt;Hello&amp;nbsp;###ChangeNAME###&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;span style=&quot;color: #aa9260;&quot;&gt;&lt;strong&gt;your Password is:&amp;nbsp;&lt;/strong&gt;&lt;/span&gt;&lt;strong&gt;###ChangePassword###&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;hr /&gt;
        ///&lt;h4&gt;&lt;span style=&quot;color: #aa9260;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewMail {
            get {
                return ResourceManager.GetString("NewMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;h4&gt;&lt;strong&gt;&lt;img src=&quot;https://i.imgur.com/zmm5CCm.png&quot; width=&quot;290&quot; height=&quot;284&quot; /&gt;&lt;/strong&gt;&lt;/h4&gt;
        ///&lt;h4&gt;&lt;span style=&quot;color: #aa9260;&quot;&gt;&lt;strong&gt;You&apos;ve got new Message from:&lt;/strong&gt;&lt;/span&gt;&amp;nbsp;&lt;strong&gt;###ChangeNAME###&lt;/strong&gt;&lt;/h4&gt;
        ///&lt;h4&gt;&lt;span style=&quot;color: #aa9260;&quot;&gt;&lt;strong&gt;E-mail to return a message:&lt;/strong&gt;&lt;/span&gt;&lt;strong&gt;&amp;nbsp;###ChangeMAIL###&lt;/strong&gt;&lt;/h4&gt;
        ///&lt;h4&gt;&amp;nbsp;&lt;/h4&gt;
        ///&lt;h4&gt;&lt;span style=&quot;color: #aa9260;&quot;&gt;&lt;strong&gt;Mail Content:&amp;nbsp;&lt;/strong&gt;&lt;/span&gt;&lt;/h4&gt;
        ///&lt;h4&gt;&lt;strong&gt;###MessageHERE###&lt;/stro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SentSPecialReq {
            get {
                return ResourceManager.GetString("SentSPecialReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap אייקון_עם_צל {
            get {
                object obj = ResourceManager.GetObject("אייקון_עם_צל", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
